# Parameters for input data
in_root_dir: /dls/k11/data/2020/cm26457-3/processing/olly/gas_hydrates/200710_unet_segmentation/datafiles
data_vol_filename: 89069_centre_384_data_uint8.h5
seg_vol_filename: 89069_centre_384_seg_uint8_lbl_fixed.h5
# Parameters for output data
out_root_dir: /dls/k11/data/2020/cm26457-3/processing/olly/gas_hydrates/200720_unet_segmentation/200720_2d_unet_multilabel
data_im_dirname: data # Name of folder that sliced data 2D images will be output to
seg_im_out_dirname: seg # Name of folder that sliced segmentation 2D images with be output to 
model_output_fn: 200720_centre_resnet34_2d_unet_multilabel_Unet256.pkl # Filename for the saved Unet Model
codes:
  [sand, brine, methane] # The label classes corresponding to labels in the segmentation
normalize: false
# Settings for Unet training
image_size: 256 # size of images in databunch used for training
weight_decay: 1e-2 # weight decay 
pct_lr_inc: 0.4 # the percentage of overall iterations where the LR is increasing
num_cyc_frozen: 10 # Number of times to run fit_one_cycle on frozen unet model
num_cyc_unfrozen: 0 # Number of times to run fit_one_cycle on unfrozen unet model
