# 
#   consensus_vals - List of consensus cutoff values for agreement between volumes 
#   e.g. if 10 is in the list a volume will be output thresholded on consensus between 10 volumes
#   normalise - If set to True, the image data will be clipped and normalised before prediction. Set to False if data is already normalised.
#   cuda_device - change this if you would like to run the prediction on a differnt GPU

consensus_vals:
  [7, 8, 9, 10, 11]
normalise: True
cuda_device: 0