# 
#   predict_folder_path - folder where the combined volume from predictions was saved
#   volume_name - Filename of the HDF5 volume to be thresholded - should be the 'final_4_volumes_combined.h5' file
#   consensus_vals - List of consensus cutoff values for agreement between volumes 
#   e.g. if 10 is in the list a volume will be output thresholded on consensus between 10 volumes


predict_folder_path: /dls/p45/data/2019/cm22981-2/processing/segmentation/win_data/200513_script_test/predict_12_ways
volume_name: 2020-06-16_final_4_volumes_combined.h5  
consensus_vals:
  [5, 6, 7]