data_dir: /home/vvw07985/k11_data/unet_dev/test_data
data_fn: BINARY_stent_downsampled_384_PRED_DATA.h5
model_dir: /home/vvw07985/k11_data/unet_dev/test_data
model_fn: 210225_3d_test_model_2_channel_multilabel.pytorch
data_out_dir: /home/vvw07985/k11_data/unet_dev/demo_dir
data_out_fn: 210225_3d_test_2_channel_data_pred.h5
hdf5_path: /data
# Parameters for generating patches
patch_size:
  [192, 192, 192]
patch_overlap: 32
padding_mode: reflect # One of [reflect, edge, circular, null]
cuda_device: 2 # The graphics card to use (between 0 and 3 for a machine with 4 GPUs)