data_dir: /dls/science/groups/imaging/i12_k11_collaboration/mt16205-1_hydrates/olly/200713_unet_segmentation/training_data
data_fn: 89069_validation_384_data_uint8.h5
model_dir: /dls/science/groups/imaging/i12_k11_collaboration/mt16205-1_hydrates/olly/200713_unet_segmentation/3dUnet/multilabel/models
model_fn: 200725_3dUnet_sand_brine_meth_multilabel_3cGDL_p30.pytorch
data_out_dir: /dls/science/groups/imaging/i12_k11_collaboration/mt16205-1_hydrates/olly/200713_unet_segmentation/3dUnet/multilabel/valid_vol_prediction/
data_out_fn: 200725_3dUnet_sand_brine_meth_multilabel_3cGDL_p30_validation_vol_predicted_ps96_ol32.h5
hdf5_path: /data
# Parameters for generating patches
patch_size:
  [96, 96, 96]
patch_overlap: 32
padding_mode: reflect # One of [reflect, edge, circular, null]
cuda_device: 0 # The graphics card to use (between 0 and 3 for a machine with 4 GPUs)
thresh_val: 0.5 # Threshold cutoff value for segmentation preview. Must be between 0 and 1.
# Parameters to control unet architecture
model:
  # model class, e.g. UNet3D, ResidualUNet3D
  name: ResidualUNet3D
  # number of input channels to the model
  in_channels: 1
  # number of output channels
  out_channels: 3
  # determines the order of operators in a single layer (gcr - GroupNorm+Conv3d+ReLU)
  layer_order: gcr
  # feature maps scale factor
  f_maps: 32
  # number of groups in the groupnorm
  num_groups: 8
  # apply element-wise nn.Sigmoid after the final 1x1 convolution, otherwise apply nn.Softmax
  final_sigmoid: false
  # if True applies the final normalization layer (sigmoid or softmax), otherwise the networks
  # returns the output from the final convolution layer; use False for regression problems, e.g. de-noising
  is_segmentation: true