# Settings for prediction of a 3d volume using a 2d model
quality: medium # One of [low, medium, high]. low = Single axis, medium = 3 axis, high = 12 ways
output_probs: False # If set to True a separate volume of probability values for the predictions will be saved alongside the labels.
clip_data: True # If set to True, the image data intensities will be clipped and rescaled before prediction. Set to False if data is already clipped.
st_dev_factor: 2.575 # Number of standard deviations from the mean to clip data to.
use_higher_bit_depth: False # Use 16bit images as intermediate format, potentially slower and uses more disk space
data_hdf5_path: /data # Internal path in the HDF5 file where the image data for prediction is stored.
cuda_device: 0 # Change this if you would like to run the prediction on a different GPU
downsample: False # If True, data will be downsampled by 2 and segmentation will be upsampled by 2
one_hot: False # Output one-hot encoded data
prediction_axis: Z # One of [Z, Y, X]. Specify axis along which to predict if doing single-axis prediction.
